---
title: "VB_Growth"
author: "Anna Haws"
date: "2024-08-19"
output: html_document
---

# ***Fast Life-Pace and Enhanced Body Size: Traits of an Established, Freshwater Round Goby Population in the Upper St. Lawrence River***
## **Anna L. Haws, John M. Farrell**

### *Von Bertalanffy growth of observed length data*

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(magrittr)
library(dplyr)
library(tidyr)
library(FSA)
library(nlstools)
library(ggplot2)
```

```{r, include=FALSE}
#Load fully processed dataset
RG <- read_excel("G:/Dissertation/Chapter 4- VHSV demographic/Anna_Haws_Traits_of_Round_Goby_in_USLR/Data/DISSECTED.xlsx") 
```


```{r, include=FALSE}
# Categorize into 5mm length classes & remove unaged records
RG %<>% mutate(lcat5=lencat(Total.Length, w=5)) %<>% filter(!is.na(RG$Age))

# Create male and female data frames
Male<- filter(RG, Sex== "M")
Female<- filter(RG, Sex=="F")

# Create von Bertalanffy nonlinear function
vbTyp <- vbFuns("typical")
```

## Male Von Bertalanffy 

### <i>model fitting</i>

```{r}
#Starting values via FSA package
(MVB <- vbStarts(Total.Length~Age,data=Male))

#fit nonlinear equation and create summary table
fitM<- nls(Total.Length~vbTyp(Age, Linf, K, t0), data=Male, start=MVB)
bM <- nlsBoot(fitM)

#bootstrap model fitting to get parameter confidence intervals
(M_param<- cbind(coef(fitM),confint(bM)))
(M_VBSum<- summary(fitM))
```

### <i>prediction and plot creation</i>

#### Male

```{r}
#Create vector of male age range
xm<- seq(min(Male$Age), max(Male$Age), length.out=199)

#Apply model to predict length at every value of x
pm<- vbTyp(xm, Linf=coef(fitM))

#Join length vector and predicted lengths into data frame
Male_VB<-as.data.frame(cbind(xm,pm))

LCI <- UCI <- numeric(length(xm))

ests<- bM$coefboot

for (i in 1:length(xm)) {
  pCI_m<-   ests[,"Linf"]*(1-exp(-ests[,"K"]*(xm[i]-ests[,"t0"])))
LCI[i] <- quantile(pCI_m,0.025)
UCI[i] <- quantile(pCI_m,0.975)
}

MVB_LCI<-as.data.frame(cbind(xm,LCI))
MVB_UCI<-as.data.frame(cbind(xm,UCI))
```

#### Female

### <i>model fitting</i>

```{r}
#Starting values via FSA package
(FVB <- vbStarts(Total.Length~Age,data=Female))

#fit nonlinear equation and create summary table
fitF<- nls(Total.Length~vbTyp(Age, Linf, K, t0), data=Female, start=FVB)
(F_VBSum<- summary(fitF))

#bootstrap model fitting to get parameter confidence intervals
bF <- nlsBoot(fitF)
(F_param<-cbind(coef(fitF),confint(bF)))

```

### <i>prediction and plot creation</i>

```{r}
#Create vector of female age range
xf<- seq(min(Female$Age), max(Female$Age), length.out=199)

#Apply model to predict length at every value of x
pf<- vbTyp(xf, Linf=coef(fitF))

#Join length vector and predicted lengths into data frame
Female_VB<-as.data.frame(cbind(xf,pf))

LCI <- UCI <- numeric(length(xf))

ests<- bF$coefboot

for (i in 1:length(xf)) {
  pCI_f<-   ests[,"Linf"]*(1-exp(-ests[,"K"]*(xf[i]-ests[,"t0"])))
LCI[i] <- quantile(pCI_f,0.025)
UCI[i] <- quantile(pCI_f,0.975)
}

FVB_LCI<-as.data.frame(cbind(xf,LCI))
FVB_UCI<-as.data.frame(cbind(xf,UCI))
```


```{r}
RG<- filter(RG, Sex!="I")

(VBPlot<- ggplot()+
   geom_point(data=RG, aes(x=Age, y=Total.Length, color=Sex)) + scale_color_manual(values = c("F" = "black", "M" = "grey")) + geom_line(data=Male_VB, aes(x=xm, y=pm), color="darkgrey") + geom_line(data=MVB_LCI, aes(x=xm, y=LCI), colour=I("darkgrey"), linetype = "dashed") + geom_line(data=MVB_UCI, aes(x=xm, y=UCI), colour=("darkgrey"), linetype = "dashed") 
 + geom_line(data=Female_VB, aes(x=xf, y=pf), color="black") + geom_line(data=FVB_LCI, aes(x=xf, y=LCI), colour=I("black"), linetype = "dashed") + geom_line(data=FVB_UCI, aes(x=xf, y=UCI), colour=I("black"), linetype = "dashed")   
+ labs(x = "Age",  y = "Total Length (mm)") + ylim(50,230)  + theme_classic () + theme(legend.position="bottom", text=element_text(size=12), legend.margin=margin(-10, 0, 0, 0))) 

VBPlot %>% ggsave(filename="VBPlot.tiff", device = "tiff", path="G:/POP_STRUCTURE_PUB/Figures/Resized_TIFFs", dpi="retina", width = 190, height = 100, units="mm")

```
